---

---

# Data Extraction Lab

---

---

Extract data with understand, configuration can be found in config.ini

## File packages

### pip installed packages

In [17]:
import git as git
import pandas as pd

 ### Local packages

In [18]:
import src.jira as my_jira
import src.hive as my_hive

## Constants loading

download_jira_data use configuration data from config.ini

Especially the filter used the select the data

---

## Downloading data from Jira website and filtering it


---

In [19]:
my_jira.download()

Data already downloaded
Filter = 'project=HIVE AND issuetype=Bug AND status in (Resolved, Closed) AND affectedVersion>= 2.0.0'

,Summary,Issue key,Issue id,Issue Type,Status,Project key,Project name,Project type,Project lead,Project description,...,Comment.53,Comment.54,Comment.55,Comment.56,Comment.57,Comment.58,Comment.59,Comment.60,Comment.61,Comment.62
0,Iceberg: Concurrent queries fail during commit...,HIVE-28515,13591603,Bug,Resolved,HIVE,Hive,software,ayushtkn,Hive is a data warehouse infrastructure built ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Outdated MetastoreSchemaTool class reference i...,HIVE-28487,13590437,Bug,Resolved,HIVE,Hive,software,ayushtkn,Hive is a data warehouse infrastructure built ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,JDBC: TableName matcher fix in GenericJdbcData...,HIVE-28451,13589308,Bug,Resolved,HIVE,Hive,software,ayushtkn,Hive is a data warehouse infrastructure built ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Iceberg: Bucket partition transform with DECIM...,HIVE-28439,13588148,Bug,Resolved,HIVE,Hive,software,ayushtkn,Hive is a data warehouse infrastructure built ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Manual import of mysql schema upgrade file fails,HIVE-28426,13587586,Bug,Resolved,HIVE,Hive,software,ayushtkn,Hive is a data warehouse infrastructure built ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2241,OrcSplit fails to account for columnar project...,HIVE-7428,12727720,Bug,Resolved,HIVE,Hive,software,ayushtkn,Hive is a data warehouse infrastructure built ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2242,Fix bug in HiveIndexedInputFormat implementati...,HIVE-7239,12721479,Bug,Closed,HIVE,Hive,software,ayushtkn,Hive is a data warehouse infrastructure built ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2243,Parse Exception : character '@' not supported ...,HIVE-4413,12644338,Bug,Resolved,HIVE,Hive,software,ayushtkn,Hive is a data warehouse infrastructure built ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2244,Fix column names in FileSinkOperator,HIVE-4243,12639596,Bug,Closed,HIVE,Hive,software,ayushtkn,Hive is a data warehouse infrastructure built ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2245,Boolean columns in Hive tables containing NULL...,HIVE-1863,12493943,Bug,Closed,HIVE,Hive,software,ayushtkn,Hive is a data warehouse infrastructure built ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
jira_dataframe = my_jira.filter_data()
jira_dataframe

Data already filtered
Data stored in 'data\jira_data\jira_filtered_data\filtered.csv'

,Issue key,Fix Versions Combined,Affects Versions Combined,Priority
0,HIVE-28515,"4.0.1, 4.1.0",4.0.0,Major
1,HIVE-28487,"4.0.1, 4.1.0",4.0.0,Minor
2,HIVE-28451,"4.0.1, 4.1.0",4.0.0,Major
3,HIVE-28439,"4.0.1, 4.1.0",4.0.0,Major
4,HIVE-28366,4.1.0,4.0.0,Major
...,...,...,...,...
1661,HIVE-10233,1.3.0,"2.0.0, llap",Major
1662,HIVE-10021,"1.3.0, 2.0.0","0.13.1, 2.0.0",Major
1663,HIVE-9499,"2.0.1, 2.1.0","0.14.0, 1.0.0, 1.1.0, 1.2.0, 2.0.0",Major
1664,HIVE-7239,2.2.0,2.1.0,Major
1665,HIVE-4243,2.0.0,"1.3.0, 2.0.0",Major

---

## Downloading Jira repository


---

In [21]:
git_repo: git.Repo = my_hive.download()

data\hive_data\hiveRepo False
Pulling the repository: https://github.com/apache/hive.git

In [22]:
bugs_ids: set = set(jira_dataframe["Issue key"])  # Get the bugs ids
list(bugs_ids)[:5]

['HIVE-13844', 'HIVE-24094', 'HIVE-22178', 'HIVE-20179', 'HIVE-13438']

In [23]:
tuples = my_hive.commit_analysis(bugs_ids) # (issue, file, commit)
pd.DataFrame(tuples, columns=["Issue key", "File", "Commit"])

Checking if Jira tuples already created.
Jira tuples already created.
Data stored in 'data\jira_data\jira_tuples\tuples.csv'

,Issue key,File,Commit
0,HIVE-21614,ql/src/test/org/apache/hadoop/hive/metastore/T...,f583467f6080f127d8c4c65ba3c407af7eba6873
1,HIVE-21614,standalone-metastore/metastore-server/src/main...,f583467f6080f127d8c4c65ba3c407af7eba6873
2,HIVE-21614,standalone-metastore/metastore-server/src/main...,f583467f6080f127d8c4c65ba3c407af7eba6873
3,HIVE-28366,iceberg/iceberg-handler/src/main/java/org/apac...,6e1f1ccf2aca58af4be06d6ceea1aa2b877a5d08
4,HIVE-28366,iceberg/iceberg-handler/src/main/java/org/apac...,6e1f1ccf2aca58af4be06d6ceea1aa2b877a5d08
...,...,...,...
19264,HIVE-14092,ql/src/java/org/apache/hadoop/hive/ql/exec/Ser...,1e7ad049954b75a4643684d95ef143bbc6d1a17f
19265,HIVE-14098,ql/src/java/org/apache/hadoop/hive/ql/exec/Uti...,44bc8e71b6b7bd6a396873b72c2f1fc872782252
19266,HIVE-14098,ql/src/java/org/apache/hadoop/hive/ql/exec/mr/...,44bc8e71b6b7bd6a396873b72c2f1fc872782252
19267,HIVE-14098,ql/src/java/org/apache/hadoop/hive/ql/exec/spa...,44bc8e71b6b7bd6a396873b72c2f1fc872782252
19268,HIVE-14098,ql/src/test/org/apache/hadoop/hive/ql/exec/Tes...,44bc8e71b6b7bd6a396873b72c2f1fc872782252